name: PixelMOTD
version: '${project.version}'
main: me.blueslime.pixelmotd.initialization.spigot.SpigotMOTD
description: Motd plugin for multiplatform
author: JustJustin
website: "https://github.com/ShieldCommunity/PixelMOTD"
softdepend:
  - ProtocolLib