#   _____ _          _ __  __  ____ _______ _____
#   |  __ (_)        | |  \/  |/ __ \__   __|  __ \
#   | |__) |__  _____| | \  / | |  | | | |  | |  | |
#   |  ___/ \ \/ / _ \ | |\/| | |  | | | |  | |  | |
#   | |   | |>  <  __/ | |  | | |__| | | |  | |__| |
#   |_|   |_/_/\_\___|_|_|  |_|\____/  |_|  |_____/
#
#   Using version 10.0.0-SNAPSHOT
#   Author: JustJustin (MrUniverse44)
#   SpigotMC Link: https://www.spigotmc.org/resources/37177/
#   MC-Market Link: https://www.mc-market.org/resources/22313/
#   GitHub Link: https://github.com/ShieldCommunity/PixelMOTD
#
enabled: false

global-kick-reason:
  - '&c&lYOU ARE NOT IN THE WHITELIST OF THIS NETWORK'
  - '&7Your username &8%username% &7is not allowed here'
  - '&7You can''t play here.'